dataset_name: thumos14
train_split: ['training']
val_split: ['validation']
dataset: {
  split_id: -1, # input proper split_id
  json_file: "./data/thumos14/annotations/train_50_test_50/validation_50-{split_id}_tal.json",
  feat_folder: ./data/thumos14/vificlip_feats/F16_w16F_s4F_ep10_trainval,
#  class_agnostic: True,
  class_agnostic: False,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 1,
  input_dim: 512,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
  default_fps: 30,
}
CLIP: {
  inf_only: True,
  weight: "./checkpoints/vifi_clip/vifi_clip_10_epochs_k400_full_finetuned.pth",
  ## inference details
  softmax: True,
#  softmax: False,
  topk: 1,
#  topk: 2,
#  nms: False,
  nms: True,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0001,
  # eta_min: 0.0001, # 1e-8
  epochs: 30,
  warmup_epochs: 5,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
  num_workers: 4,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  run_val: True,
}
test_cfg: {
  nms_method: 'none',
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: False,
}
# ckpt_folder: ./ckpt/path_to_ckpt
ckpt_folder: "./ckpt/TH_agn_50/thumos14_vifi_prop_50_tmpl_split{split_id}_0_ema"
#ckpt_folder: "./ckpt/TH_agn_50/thumos14_vifi_prop_50_tmpl_split{split_id}_1_ema"
#ckpt_folder: "./ckpt/TH_agn_PL_50/thumos14_vifi_prop_50_pseudo_tmpl_split{split_id}_0_ema_th0.05"