dataset_name: fineaction
train_split: ['training']
val_split: ['validation']
dataset: {
  train_json_file: ./data/fineaction/annotations/training_K400_tal.json,
  val_json_file: ./data/fineaction/annotations/validation_K400_tal.json,
  feat_folder: ./data/fineaction/vificlip_feats/F16_w16F_s4F_clip_trainval,
  file_prefix: ~,
  file_ext: .npy,
  num_classes: 56,
  input_dim: 512,
  feat_stride: 4,
  num_frames: 16,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 2304,
  default_fps: 30,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 28.0, # max: 56843 - 2048*28 = 57344
  n_mha_win_size: 19,
}
opt: {
  learning_rate: 0.0001,
  epochs: 3,
  weight_decay: 0.05,
  warmup_epochs: 5,
  eta_min: 0.00001 # 1e-8
}
loader: {
  batch_size: 2,
  num_workers: 8,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
  run_val: True
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ./ckpt/cls_aware
